/**
 * Regenerate `shared/src/api.zod.ts` from the interfaces in `shared/src/api.ts`.
 *
 * ts-to-zod resolves imported types to `any`, so the three imported string unions
 * are inlined into a scratch copy first; `shared/test/api.contract.test.ts` proves
 * the inlined copies still match the originals.
 *
 * Not `zod/mini`: Metro does not tree-shake, so `zod/v4/core` ships either way —
 * measured 407 KB gzipped against classic zod's 412 KB.
 *
 * `--skipValidation`: the generator's own validate step type-checks against
 * whichever `zod` it resolves first — the v3 Expo pulls in, not the v4 `shared`
 * uses — and fails on that mismatch alone.
 */

import { execFileSync } from "node:child_process";
import { readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = resolve(ROOT, "shared/src/api.ts");
/** Import nothing, so unlike `api.ts` they need no inlining pass. */
const DATA_CONTRACT_SOURCES = ["domain", "predictions"] as const;
const SCRATCH = resolve(ROOT, "shared/src/api.gen-input.ts");
const OUTPUT = resolve(ROOT, "shared/src/api.zod.ts");

const IMPORTED_UNIONS = `export type Direction = "inbound" | "outbound";
export type VehicleStopStatus = "incoming_at" | "stopped_at" | "in_transit_to";
export type HeatmapType = "hour_of_day" | "day_of_week";
export type CertificateBand = "early" | "am_peak" | "midday" | "pm_peak" | "evening";`;

const IMPORTS = `import type { Direction, VehicleStopStatus } from "./domain";
import type { CertificateBand, HeatmapType } from "./constants";`;

const HEADER = `/**
 * Runtime validators for the API contract in \`api.ts\`.
 *
 * GENERATED by ts-to-zod (\`npm run generate:contract\`) — edit \`api.ts\`, not
 * this file. They exist because api and app deploy independently and can run
 * different versions of the contract at once, which TypeScript cannot see; a
 * renamed field would otherwise reach the other side as \`undefined\`.
 */
import { z } from "zod";`;

const source = readFileSync(SOURCE, "utf8");
if (!source.includes(IMPORTS)) {
  throw new Error(
    "api.ts no longer imports the union types this script inlines — update IMPORTS/IMPORTED_UNIONS.",
  );
}

writeFileSync(SCRATCH, source.replace(IMPORTS, IMPORTED_UNIONS));
try {
  execFileSync(
    "npx",
    // ts-to-zod joins its arguments onto cwd even when they are absolute.
    ["ts-to-zod", "shared/src/api.gen-input.ts", "shared/src/api.zod.ts", "--keepComments", "--skipValidation"],
    { cwd: ROOT, stdio: "inherit" },
  );
} finally {
  rmSync(SCRATCH, { force: true });
}

const generated = readFileSync(OUTPUT, "utf8");
// Assert rather than replace-and-hope: a silent no-op here ships a generated
// file with no "do not edit" warning, and nothing else would fail.
const TS_TO_ZOD_HEADER = `// Generated by ts-to-zod\nimport { z } from "zod";`;
if (!generated.startsWith(TS_TO_ZOD_HEADER)) {
  throw new Error("ts-to-zod's header changed shape — update TS_TO_ZOD_HEADER.");
}
writeFileSync(OUTPUT, HEADER + generated.slice(TS_TO_ZOD_HEADER.length));

console.log(`Wrote ${OUTPUT}`);

for (const name of DATA_CONTRACT_SOURCES) {
  execFileSync("npx", ["ts-to-zod", `shared/src/${name}.ts`, `shared/src/${name}.zod.ts`, "--keepComments", "--skipValidation"], {
    cwd: ROOT,
    stdio: "inherit",
  });
  console.log(`Wrote shared/src/${name}.zod.ts`);
}
