/**
 * Regenerate `shared/src/api.zod.ts` from the interfaces in `shared/src/api.ts`.
 *
 * ts-to-zod resolves imported types to `any`, and the contract imports three
 * string unions (`Direction`, `VehicleStopStatus`, `HeatmapType`). They are
 * inlined into a scratch copy so the generator can see their members, then the
 * copy is deleted — the generated file ends up self-contained, and
 * `shared/test/api.contract.test.ts` proves the inlined copies still match the
 * originals.
 *
 * `zod/mini` is not worth reaching for here. It bundles at 4 KB gzipped against
 * classic zod's 63 KB under esbuild, but Metro does not tree-shake, so it ships
 * the whole of `zod/v4/core` either way: converting the generated output to
 * mini's `z.nullable(x)` form measured 407 KB gzipped against classic zod's
 * 412 KB. Five kilobytes does not pay for a bespoke expression rewriter and a
 * non-idiomatic API leaking into the app.
 *
 * The generator's own `--validate` step is skipped: it type-checks the output
 * against whichever `zod` it resolves first, which in this workspace is the v3
 * that Expo pulls in rather than the v4 `shared` depends on, and it fails on
 * that mismatch alone. The contract test replaces it with a stronger check that
 * runs on every typecheck rather than only at generation time.
 */

import { execFileSync } from "node:child_process";
import { readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE = resolve(ROOT, "shared/src/api.ts");
/**
 * Self-contained modules that also need runtime schemas, for the object-storage
 * contract shared with the Python modelling repo. They import nothing, so unlike
 * `api.ts` they need no inlining pass.
 */
const DATA_CONTRACT_SOURCES = ["domain", "predictions"] as const;
const SCRATCH = resolve(ROOT, "shared/src/api.gen-input.ts");
const OUTPUT = resolve(ROOT, "shared/src/api.zod.ts");

const IMPORTED_UNIONS = `export type Direction = "inbound" | "outbound";
export type VehicleStopStatus = "incoming_at" | "stopped_at" | "in_transit_to";
export type HeatmapType = "hour_of_day" | "day_of_week";`;

const IMPORTS = `import type { Direction, VehicleStopStatus } from "./domain";
import type { HeatmapType } from "./constants";`;

const HEADER = `/**
 * Runtime validators for the API contract in \`api.ts\`.
 *
 * GENERATED by ts-to-zod (\`npm run generate:contract\`) — edit \`api.ts\`, not
 * this file. The interfaces there stay the human-readable contract, with the
 * doc comments explaining what each field means; these are their runtime
 * shadow, for the one place types cannot help.
 *
 * That place is deployment skew. The API ships to Fly and the web app to
 * Cloudflare Pages, independently, so the two can be running different
 * versions of this contract at the same time. TypeScript checks each build in
 * isolation and has nothing to say about the pair; a field renamed on one side
 * reaches the other as \`undefined\` and renders as a blank panel rather than an
 * error. \`api.contract.test.ts\` proves these schemas still match the
 * interfaces, so a drift between them fails the build instead.
 */
import { z } from "zod";`;

const source = readFileSync(SOURCE, "utf8");
if (!source.includes(IMPORTS)) {
  throw new Error(
    "api.ts no longer imports the union types this script inlines — update IMPORTS/IMPORTED_UNIONS.",
  );
}

writeFileSync(SCRATCH, source.replace(IMPORTS, IMPORTED_UNIONS));
try {
  execFileSync(
    "npx",
    // ts-to-zod joins its arguments onto cwd even when they are absolute.
    ["ts-to-zod", "shared/src/api.gen-input.ts", "shared/src/api.zod.ts", "--keepComments", "--skipValidation"],
    { cwd: ROOT, stdio: "inherit" },
  );
} finally {
  rmSync(SCRATCH, { force: true });
}

const generated = readFileSync(OUTPUT, "utf8");
const generatedHeader = `// Generated by ts-to-zod
import { z } from "zod";

/**
 * API response DTOs. These are the contract between the backend API and the
 * Expo frontend. The frontend imports these types directly; it never imports
 * the db or domain-storage types.
 */`;
writeFileSync(OUTPUT, generated.replace(generatedHeader, HEADER));

console.log(`Wrote ${OUTPUT}`);

for (const name of DATA_CONTRACT_SOURCES) {
  execFileSync("npx", ["ts-to-zod", `shared/src/${name}.ts`, `shared/src/${name}.zod.ts`, "--keepComments", "--skipValidation"], {
    cwd: ROOT,
    stdio: "inherit",
  });
  console.log(`Wrote shared/src/${name}.zod.ts`);
}
