/**
 * Runtime validators for the API contract in `api.ts`.
 *
 * GENERATED by ts-to-zod (`npm run generate:contract`) — edit `api.ts`, not
 * this file. They exist because api and app deploy independently and can run
 * different versions of the contract at once, which TypeScript cannot see; a
 * renamed field would otherwise reach the other side as `undefined`.
 */
import { z } from "zod";

export const directionSchema = z.union([z.literal("inbound"), z.literal("outbound")]);

export const vehicleStopStatusSchema = z.union([z.literal("incoming_at"), z.literal("stopped_at"), z.literal("in_transit_to")]);

export const heatmapTypeSchema = z.union([z.literal("hour_of_day"), z.literal("day_of_week")]);

export const distributionBucketResultSchema = z.object({
    label: z.string(),
    count: z.number()
});

export const otpThresholdResultSchema = z.object({
    thresholdSeconds: z.number(),
    thresholdMinutes: z.number(),
    otpPercent: z.number(),
    onTimeTrips: z.number()
});

export const otpSummarySchema = z.object({
    tripsOperated: z.number(),
    tripsCancelled: z.number(),
    cancellationRatePercent: z.number(),
    avgDelaySeconds: z.number(),
    medianDelaySeconds: z.number(),
    p90DelaySeconds: z.number(),
    thresholds: z.array(otpThresholdResultSchema),
    delayDistribution: z.array(distributionBucketResultSchema)
});

/**
 * NJT publishes performance data months in arrears, so a "last 30 days" window
 * routinely covers no published month; the API falls back to the most recent
 * published one and reports it here so the UI can label the fallback.
 */
export const publishedCoverageSchema = z.object({
    /** `YYYY-MM`. */
    fromMonth: z.string(),
    toMonth: z.string(),
    outsideRequestedRange: z.boolean()
});

export const njtOfficialComparisonSchema = z.object({
    thresholdSeconds: z.number(),
    otpPercent: z.number(),
    otpPercentAmtrakAdjusted: z.number().nullable(),
    monthsCovered: z.number(),
    tripsOperated: z.number(),
    cancellations: z.number(),
    cancellationRatePercent: z.number()
});

export const cancellationCauseResultSchema = z.object({
    cause: z.string(),
    count: z.number(),
    percent: z.number()
});

export const njtCancellationsSchema = z.object({
    total: z.number(),
    byCause: z.array(cancellationCauseResultSchema),
    monthsCovered: z.number()
});

export const fleetMdbfSchema = z.object({
    avgMiles: z.number(),
    monthsCovered: z.number()
});

export const heatmapBucketResultSchema = z.object({
    bucket: z.number(),
    label: z.string(),
    avgDelaySeconds: z.number(),
    observations: z.number()
});

export const feedHealthSchema = z.object({
    feedType: z.string(),
    lastSuccessAtMs: z.number().nullable(),
    lastFailureAtMs: z.number().nullable(),
    pollsToday: z.number(),
    failuresToday: z.number()
});

export const dataGapSchema = z.object({
    feedType: z.string(),
    startMs: z.number(),
    endMs: z.number()
});

export const officialCoverageSchema = z.object({
    lineName: z.string(),
    firstMonth: z.string().nullable(),
    lastMonth: z.string().nullable(),
    monthsPresent: z.number(),
    monthsExpected: z.number(),
    missingMonths: z.array(z.string())
});

export const healthResponseSchema = z.object({
    collectionStartDate: z.string().nullable(),
    uptimePercent: z.number(),
    feeds: z.array(feedHealthSchema),
    knownGaps: z.array(dataGapSchema),
    officialCoverage: z.array(officialCoverageSchema),
    generatedAtMs: z.number()
});

export const mapStationSchema = z.object({
    stopId: z.string(),
    stopName: z.string(),
    lat: z.number(),
    lon: z.number()
});

export const mapLineSchema = z.object({
    lineId: z.string(),
    name: z.string(),
    shortName: z.string(),
    mode: z.union([z.literal("rail"), z.literal("light_rail")]),
    /** Official NJT route color (hex, no leading #). */
    color: z.string(),
    njtOtpPercent: z.number().nullable(),
    /** Independent (measured) OTP at the 15-min threshold. */
    projectOtpPercent15Min: z.number().nullable(),
    /** Ordered stop ids tracing the line's path (keys into `stations`). */
    path: z.array(z.string())
});

export const mapResponseSchema = z.object({
    from: z.string(),
    to: z.string(),
    stations: z.array(mapStationSchema),
    lines: z.array(mapLineSchema)
});

export const mapVehicleSchema = z.object({
    vehicleId: z.string(),
    tripId: z.string().nullable(),
    routeId: z.string().nullable(),
    lineName: z.string().nullable(),
    direction: directionSchema.nullable(),
    latitude: z.number(),
    longitude: z.number(),
    bearing: z.number().nullable(),
    speedMph: z.number().nullable(),
    stopId: z.string().nullable(),
    stopName: z.string().nullable(),
    status: vehicleStopStatusSchema.nullable(),
    /** When the train reported this position, epoch seconds UTC. */
    reportedAt: z.number().nullable(),
    ageSeconds: z.number().nullable()
});

export const mapVehiclesResponseSchema = z.object({
    vehicles: z.array(mapVehicleSchema),
    lastIngestedAtMs: z.number().nullable(),
    generatedAtMs: z.number()
});

export const departureStatusSchema = z.union([z.literal("on_time"), z.literal("late"), z.literal("early"), z.literal("cancelled"), z.literal("skipped"), z.literal("scheduled")]);

export const departureSchema = z.object({
    tripId: z.string(),
    lineId: z.string(),
    lineName: z.string(),
    direction: directionSchema,
    /** GTFS headsign; null when the trip is unmatched. */
    destination: z.string().nullable(),
    /** Timetabled departure (falls back to arrival), epoch seconds UTC. */
    scheduledTime: z.number().nullable(),
    /** The feed's live prediction, epoch seconds UTC. Null when cancelled. */
    predictedTime: z.number().nullable(),
    /** Positive = late. Null when the feed offers no prediction. */
    delaySeconds: z.number().nullable(),
    /** Whole minutes until `predictedTime`; negative once it is due. */
    minutesAway: z.number().nullable(),
    status: departureStatusSchema
});

export const stationDeparturesResponseSchema = z.object({
    stopId: z.string(),
    stopName: z.string(),
    departures: z.array(departureSchema),
    horizonMinutes: z.number(),
    generatedAtMs: z.number()
});

export const trendDirectionSchema = z.union([z.literal("improving"), z.literal("worsening"), z.literal("stable")]);

export const lineTrendSchema = z.object({
    lineId: z.string(),
    lineName: z.string(),
    recentOtpPercent: z.number().nullable(),
    /** The equal-length period immediately before it. */
    priorOtpPercent: z.number().nullable(),
    /** Percentage points, recent minus prior. */
    deltaPoints: z.number().nullable(),
    recentTrips: z.number(),
    priorTrips: z.number(),
    /** "stable" also covers changes too small or too noisy to call. */
    direction: trendDirectionSchema,
    enoughData: z.boolean()
});

export const trendsResponseSchema = z.object({
    days: z.number(),
    recentFrom: z.string(),
    recentTo: z.string(),
    priorFrom: z.string(),
    priorTo: z.string(),
    thresholdSeconds: z.number(),
    lines: z.array(lineTrendSchema)
});

export const stationRankingSortSchema = z.union([z.literal("delay"), z.literal("amplification")]);

export const stationRankingSchema = z.object({
    stopId: z.string(),
    stopName: z.string(),
    lines: z.array(z.string()),
    avgArrivalDelaySeconds: z.number(),
    observations: z.number(),
    /**
     * Share of trains that arrived on time but left late — delay the station
     * itself introduces, rather than delay it inherited from up the line.
     */
    amplificationRatePercent: z.number().nullable(),
    arrivedWithin5Min: z.number(),
    lowSample: z.boolean()
});

export const stationRankingsResponseSchema = z.object({
    from: z.string(),
    to: z.string(),
    sort: stationRankingSortSchema,
    stations: z.array(stationRankingSchema),
    excludedLowSample: z.number()
});

/** Average delay at one stop along a line's route, in running order. */
export const propagationStopSchema = z.object({
    stopId: z.string(),
    stopName: z.string(),
    /** Position along the route, 1-based. */
    sequence: z.number(),
    avgDelaySeconds: z.number().nullable(),
    observations: z.number(),
    /**
     * Change in average delay since the previous stop; positive = this segment
     * added delay. Null at the first stop.
     */
    deltaSeconds: z.number().nullable()
});

export const propagationSegmentSchema = z.object({
    fromStopName: z.string(),
    toStopName: z.string(),
    addedSeconds: z.number()
});

export const propagationResponseSchema = z.object({
    lineId: z.string(),
    lineName: z.string(),
    direction: directionSchema,
    from: z.string(),
    to: z.string(),
    stops: z.array(propagationStopSchema),
    /** Segments that add the most delay, worst first. */
    worstSegments: z.array(propagationSegmentSchema),
    /** Segments where trains most reliably make time back. */
    bestRecoveries: z.array(propagationSegmentSchema),
    /** Delay at the last stop minus the first. */
    netAccumulatedSeconds: z.number().nullable()
});

export const commuteDepartureSchema = z.object({
    /** Minutes after local midnight. */
    departureMinutes: z.number(),
    /** "7:42 AM". */
    label: z.string(),
    lineName: z.string(),
    scheduledMinutes: z.number().nullable(),
    observations: z.number(),
    cancellations: z.number(),
    /** Share arriving within the strict threshold. Null below the sample floor. */
    onTimePercent: z.number().nullable(),
    avgArrivalDelaySeconds: z.number().nullable(),
    p90ArrivalDelaySeconds: z.number().nullable(),
    lowSample: z.boolean()
});

export const commuteResponseSchema = z.object({
    origin: z.object({
        stopId: z.string(),
        stopName: z.string()
    }),
    destination: z.object({
        stopId: z.string(),
        stopName: z.string()
    }),
    from: z.string(),
    to: z.string(),
    /** Lines that actually ran this pair in the period. */
    linesServing: z.array(z.string()),
    observations: z.number(),
    cancellations: z.number(),
    cancellationRatePercent: z.number(),
    onTimePercent: z.number().nullable(),
    avgArrivalDelaySeconds: z.number().nullable(),
    p90ArrivalDelaySeconds: z.number().nullable(),
    /** Median observed journey time, minutes. */
    medianJourneyMinutes: z.number().nullable(),
    /** Timetabled journey time, minutes. */
    scheduledJourneyMinutes: z.number().nullable(),
    /** Every timetabled departure on this pair, earliest first. */
    departures: z.array(commuteDepartureSchema),
    mostReliable: commuteDepartureSchema.nullable(),
    leastReliable: commuteDepartureSchema.nullable()
});

export const lightRailLineMdbfSchema = z.object({
    lineName: z.string(),
    avgMdbf: z.number(),
    monthsCovered: z.number()
});

export const lightRailSummaryResponseSchema = z.object({
    from: z.string(),
    to: z.string(),
    /** Average systemwide light-rail OTP over the period. */
    otpPercent: z.number().nullable(),
    monthsCovered: z.number(),
    lines: z.array(lightRailLineMdbfSchema),
    /** Monthly systemwide light-rail OTP over the period, ascending. */
    otpTrend: z.array(z.object({
        month: z.string(),
        otpPercent: z.number()
    })),
    coverage: publishedCoverageSchema.nullable()
});

export const systemSummaryResponseSchema = z.object({
    from: z.string(),
    to: z.string(),
    overall: otpSummarySchema,
    njtOfficial: njtOfficialComparisonSchema.nullable(),
    njtCancellations: njtCancellationsSchema.nullable(),
    fleetMdbf: fleetMdbfSchema.nullable(),
    /** Months `njtOfficial` / `njtCancellations` cover. */
    officialCoverage: publishedCoverageSchema.nullable(),
    /** Months `fleetMdbf` covers (published separately from per-line OTP). */
    fleetMdbfCoverage: publishedCoverageSchema.nullable()
});

export const heatmapResponseSchema = z.object({
    from: z.string(),
    to: z.string(),
    type: heatmapTypeSchema,
    buckets: z.array(heatmapBucketResultSchema)
});

export const lineListItemSchema = z.object({
    /** Public identifier used in API paths and deep links (the GTFS route_id). */
    id: z.string(),
    slug: z.string(),
    name: z.string(),
    shortName: z.string(),
    hasAmtrakAttribution: z.boolean(),
    /** Official NJT route color (hex, no leading #). */
    color: z.string().nullable(),
    /** NJT's reported OTP for the most recent published month. */
    njtOtpPercent: z.number().nullable(),
    njtCancellationRatePercent: z.number().nullable(),
    /** The month those NJT figures are from, `YYYY-MM`. */
    njtLatestMonth: z.string().nullable()
});

export const lineListResponseSchema = z.object({
    lines: z.array(lineListItemSchema)
});

export const lineSummaryResponseSchema = z.object({
    lineId: z.string(),
    name: z.string(),
    from: z.string(),
    to: z.string(),
    overall: otpSummarySchema,
    inbound: otpSummarySchema,
    outbound: otpSummarySchema,
    njtOfficial: njtOfficialComparisonSchema.nullable(),
    njtCancellations: njtCancellationsSchema.nullable(),
    /** Months `njtOfficial` / `njtCancellations` cover. */
    officialCoverage: publishedCoverageSchema.nullable()
});

export const trendPointSchema = z.object({
    date: z.string(),
    otpPercent15Min: z.number(),
    cancellationRatePercent: z.number(),
    tripsOperated: z.number(),
    /** NJT's reported 6-min OTP for the month this point falls in. */
    njtOfficialOtpPercent: z.number().nullable()
});

export const lineTrendResponseSchema = z.object({
    lineId: z.string(),
    from: z.string(),
    to: z.string(),
    interval: z.union([z.literal("daily"), z.literal("weekly")]),
    njtThresholdSeconds: z.number(),
    points: z.array(trendPointSchema)
});

export const monthlyComparisonRowSchema = z.object({
    /** `YYYY-MM`. */
    month: z.string(),
    /** NJT's reported 6-minute OTP for the month. */
    njtOtpPercent: z.number().nullable(),
    njtOtpPercentAmtrakAdjusted: z.number().nullable(),
    /** This project's OTP at the 15-minute threshold. */
    projectOtpPercent15Min: z.number().nullable(),
    projectTripsOperated: z.number()
});

export const lineMonthlyResponseSchema = z.object({
    lineId: z.string(),
    name: z.string(),
    rows: z.array(monthlyComparisonRowSchema)
});

/** Average NJT OTP for a calendar month across all available years. */
export const seasonalityMonthSchema = z.object({
    /** 1-12. */
    month: z.number(),
    avgOtpPercent: z.number().nullable(),
    years: z.number()
});

export const annualOtpYearSchema = z.object({
    year: z.number(),
    avgOtpPercent: z.number().nullable(),
    months: z.number()
});

export const historyResponseSchema = z.object({
    scopeLabel: z.string(),
    seasonality: z.array(seasonalityMonthSchema),
    annual: z.array(annualOtpYearSchema),
    /** Fleet mean-distance-between-failures by year (system scope only). */
    mdbfAnnual: z.union([z.array(z.object({
            year: z.number(),
            avgMdbf: z.number()
        })), z.undefined()]).optional()
});

export const worstTripSchema = z.object({
    tripId: z.string(),
    routeId: z.string(),
    lineName: z.string(),
    direction: directionSchema,
    terminalStopName: z.string(),
    avgTerminalDelaySeconds: z.number(),
    observations: z.number()
});

export const worstTripsResponseSchema = z.object({
    scopeLabel: z.string(),
    from: z.string(),
    to: z.string(),
    trips: z.array(worstTripSchema)
});

export const stationListItemSchema = z.object({
    stopId: z.string(),
    stopName: z.string(),
    lines: z.array(z.string())
});

export const stationListResponseSchema = z.object({
    stations: z.array(stationListItemSchema)
});

export const stationLineDirectionDelaySchema = z.object({
    lineName: z.string(),
    direction: directionSchema,
    avgArrivalDelaySeconds: z.number(),
    observations: z.number()
});

export const stationSummaryResponseSchema = z.object({
    stopId: z.string(),
    stopName: z.string(),
    from: z.string(),
    to: z.string(),
    byLineDirection: z.array(stationLineDirectionDelaySchema),
    delayDistribution: z.array(distributionBucketResultSchema),
    hourOfDay: z.array(heatmapBucketResultSchema),
    amplification: z.object({
        arrivedWithin5Min: z.number(),
        departedLate: z.number(),
        amplificationRatePercent: z.number()
    })
});

export const connectionDayOfWeekResultSchema = z.object({
    dayOfWeek: z.number(),
    observations: z.number(),
    successes: z.number(),
    successRatePercent: z.number()
});

export const connectionRateResultSchema = z.object({
    observations: z.number(),
    successes: z.number(),
    successRatePercent: z.number()
});

export const connectionResponseSchema = z.object({
    inboundTripId: z.string(),
    transferStopId: z.string(),
    outboundTripId: z.string(),
    from: z.string(),
    to: z.string(),
    observations: z.number(),
    successes: z.number(),
    successRatePercent: z.number(),
    byDayOfWeek: z.array(connectionDayOfWeekResultSchema),
    peak: connectionRateResultSchema,
    offPeak: connectionRateResultSchema,
    inboundDelayDistribution: z.array(distributionBucketResultSchema),
    lowSample: z.boolean()
});

export const connectionTopItemSchema = z.object({
    inboundTripId: z.string(),
    transferStopId: z.string(),
    transferStopName: z.string(),
    outboundTripId: z.string(),
    observations: z.number()
});

export const connectionTopResponseSchema = z.object({
    transfers: z.array(connectionTopItemSchema)
});

export const alertListItemSchema = z.object({
    alertId: z.string(),
    affectedRoutes: z.array(z.string()),
    affectedStops: z.array(z.string()),
    headerText: z.string(),
    descriptionText: z.string(),
    effectType: z.string(),
    activeFrom: z.number().nullable(),
    activeTo: z.number().nullable(),
    ingestedAtMs: z.number()
});

export const alertListResponseSchema = z.object({
    alerts: z.array(alertListItemSchema),
    page: z.number(),
    pageSize: z.number(),
    total: z.number()
});

export const alertFrequencyLineSchema = z.object({
    lineName: z.string(),
    counts: z.record(z.string(), z.number()),
    total: z.number()
});

export const alertFrequencyResponseSchema = z.object({
    from: z.string(),
    to: z.string(),
    byLine: z.array(alertFrequencyLineSchema)
});

/**
 * The range a model puts a delay in. Null where the run produced only a point
 * estimate, which is most days until the modelling repo publishes intervals.
 */
export const predictionIntervalSchema = z.object({
    /** Lower bound, seconds; positive = late. */
    lowerSeconds: z.number(),
    /** Upper bound, seconds. */
    upperSeconds: z.number(),
    /** Coverage: 80 means 8 runs in 10 are expected to land inside the range. */
    percent: z.number()
});

export const predictedDelaySchema = z.object({
    tripId: z.string(),
    lineName: z.string(),
    fromStopName: z.string(),
    toStopName: z.string(),
    /** How far ahead the prediction reaches, in seconds. */
    horizonSeconds: z.number(),
    /**
     * Scheduled arrival at `toStopName` as GTFS "HH:MM:SS", the key the list is
     * ordered by. Hours pass 24 for a trip running into the next day. Null when the
     * timetable holds no entry for this leg.
     */
    scheduledArrivalTime: z.string().nullable(),
    /** Predicted delay at the destination, seconds; positive = late. */
    predictedDelaySeconds: z.number(),
    interval: predictionIntervalSchema.nullable(),
    /** Observed delay once the trip has run, or null while it is still ahead. */
    actualDelaySeconds: z.number().nullable(),
    /** Signed error once both are known: positive = the model was optimistic. */
    errorSeconds: z.number().nullable()
});

export const predictionProvenanceSchema = z.object({
    modelVersion: z.string(),
    runId: z.string(),
    /** When the most recent prediction was made, epoch seconds UTC. */
    predictedAtEpochSeconds: z.number()
});

/**
 * `GET /predictions?date=` — model output for one service date. `available:
 * false` is the normal state until the modelling repo has run, not an error.
 */
export const predictionsResponseSchema = z.object({
    serviceDate: z.string(),
    available: z.boolean(),
    /** Service dates that do hold predictions, so a screen can offer them. */
    availableDates: z.array(z.string()),
    lines: z.array(z.string()),
    provenance: predictionProvenanceSchema.nullable(),
    /**
     * Every leg held for the service date, ordered by scheduled arrival — the order
     * a rider meets them, so theirs can be found. Pass `limit` to take a prefix.
     */
    predictions: z.array(predictedDelaySchema),
    totalPredictions: z.number(),
    /** Mean absolute error over the legs whose actual is known. */
    meanAbsoluteErrorSeconds: z.number().nullable(),
    /** How many legs have an actual to compare against. */
    scoredCount: z.number()
});
