/**
 * Runtime validators for the API contract in `api.ts`.
 *
 * GENERATED by ts-to-zod (`npm run generate:contract`) — edit `api.ts`, not
 * this file. The interfaces there stay the human-readable contract, with the
 * doc comments explaining what each field means; these are their runtime
 * shadow, for the one place types cannot help.
 *
 * That place is deployment skew. The API ships to Fly and the web app to
 * Cloudflare Pages, independently, so the two can be running different
 * versions of this contract at the same time. TypeScript checks each build in
 * isolation and has nothing to say about the pair; a field renamed on one side
 * reaches the other as `undefined` and renders as a blank panel rather than an
 * error. `api.contract.test.ts` proves these schemas still match the
 * interfaces, so a drift between them fails the build instead.
 */
import { z } from "zod";
export const directionSchema = z.union([z.literal("inbound"), z.literal("outbound")]);

export const vehicleStopStatusSchema = z.union([z.literal("incoming_at"), z.literal("stopped_at"), z.literal("in_transit_to")]);

export const heatmapTypeSchema = z.union([z.literal("hour_of_day"), z.literal("day_of_week")]);

export const distributionBucketResultSchema = z.object({
    label: z.string(),
    count: z.number()
});

export const otpThresholdResultSchema = z.object({
    thresholdSeconds: z.number(),
    thresholdMinutes: z.number(),
    otpPercent: z.number(),
    onTimeTrips: z.number()
});

/** Shared OTP block used by system, line, and direction summaries. */
export const otpSummarySchema = z.object({
    tripsOperated: z.number(),
    tripsCancelled: z.number(),
    cancellationRatePercent: z.number(),
    avgDelaySeconds: z.number(),
    medianDelaySeconds: z.number(),
    p90DelaySeconds: z.number(),
    thresholds: z.array(otpThresholdResultSchema),
    delayDistribution: z.array(distributionBucketResultSchema)
});

/**
 * Which months an official (NJT-published, monthly) figure actually covers.
 *
 * NJT publishes performance data months in arrears, so the default "last 30
 * days" window routinely contains no published months at all. Rather than
 * render an empty panel, the API falls back to the most recent published month
 * and reports that here — the UI must label a fallback so the figure is never
 * mistaken for the requested period.
 */
export const publishedCoverageSchema = z.object({
    /** `YYYY-MM`. */
    fromMonth: z.string(),
    toMonth: z.string(),
    /** True when these months fall outside the requested date range. */
    outsideRequestedRange: z.boolean()
});

/** NJT's own reported figure for the period, for side-by-side comparison. */
export const njtOfficialComparisonSchema = z.object({
    thresholdSeconds: z.number(),
    otpPercent: z.number(),
    otpPercentAmtrakAdjusted: z.number().nullable(),
    monthsCovered: z.number(),
    /** Real, NJT-reported operations totals over the covered months. */
    tripsOperated: z.number(),
    cancellations: z.number(),
    cancellationRatePercent: z.number()
});

export const cancellationCauseResultSchema = z.object({
    cause: z.string(),
    count: z.number(),
    percent: z.number()
});

/** NJT's reported cancellations for the period, broken down by cause. */
export const njtCancellationsSchema = z.object({
    total: z.number(),
    byCause: z.array(cancellationCauseResultSchema),
    monthsCovered: z.number()
});

/** Systemwide fleet reliability for the period. */
export const fleetMdbfSchema = z.object({
    avgMiles: z.number(),
    monthsCovered: z.number()
});

export const heatmapBucketResultSchema = z.object({
    bucket: z.number(),
    label: z.string(),
    avgDelaySeconds: z.number(),
    observations: z.number()
});

// --- Health -----------------------------------------------------------------
export const feedHealthSchema = z.object({
    feedType: z.string(),
    lastSuccessAtMs: z.number().nullable(),
    lastFailureAtMs: z.number().nullable(),
    pollsToday: z.number(),
    failuresToday: z.number()
});

export const dataGapSchema = z.object({
    feedType: z.string(),
    startMs: z.number(),
    endMs: z.number()
});

/** Completeness of NJT's published monthly data for a line (detects gaps). */
export const officialCoverageSchema = z.object({
    lineName: z.string(),
    firstMonth: z.string().nullable(),
    lastMonth: z.string().nullable(),
    monthsPresent: z.number(),
    monthsExpected: z.number(),
    missingMonths: z.array(z.string())
});

export const healthResponseSchema = z.object({
    collectionStartDate: z.string().nullable(),
    uptimePercent: z.number(),
    feeds: z.array(feedHealthSchema),
    knownGaps: z.array(dataGapSchema),
    officialCoverage: z.array(officialCoverageSchema),
    generatedAtMs: z.number()
});

// --- Map ---------------------------------------------------------------------
export const mapStationSchema = z.object({
    stopId: z.string(),
    stopName: z.string(),
    lat: z.number(),
    lon: z.number()
});

export const mapLineSchema = z.object({
    /** Catalog route id, for deep-linking to Line Detail. */
    lineId: z.string(),
    name: z.string(),
    shortName: z.string(),
    mode: z.union([z.literal("rail"), z.literal("light_rail")]),
    /** Official NJT route color (hex, no leading #). */
    color: z.string(),
    /** Real NJT OTP for the period (drives reliability coloring), null if none. */
    njtOtpPercent: z.number().nullable(),
    /** Independent (measured) OTP at the 15-min threshold, null if none. */
    projectOtpPercent15Min: z.number().nullable(),
    /** Ordered stop ids tracing the line's path (keys into `stations`). */
    path: z.array(z.string())
});

export const mapResponseSchema = z.object({
    from: z.string(),
    to: z.string(),
    stations: z.array(mapStationSchema),
    lines: z.array(mapLineSchema)
});

/** One train's current position, for the live map. */
export const mapVehicleSchema = z.object({
    vehicleId: z.string(),
    tripId: z.string().nullable(),
    routeId: z.string().nullable(),
    lineName: z.string().nullable(),
    direction: directionSchema.nullable(),
    latitude: z.number(),
    longitude: z.number(),
    bearing: z.number().nullable(),
    /** Converted from the feed's metres/second for display. */
    speedMph: z.number().nullable(),
    stopId: z.string().nullable(),
    stopName: z.string().nullable(),
    status: vehicleStopStatusSchema.nullable(),
    /** When the train reported this position, epoch seconds UTC. */
    reportedAt: z.number().nullable(),
    /** Seconds between the reading and this response — staleness, made visible. */
    ageSeconds: z.number().nullable()
});

export const mapVehiclesResponseSchema = z.object({
    vehicles: z.array(mapVehicleSchema),
    /** When the newest reading in this set was ingested, epoch ms (null if empty). */
    lastIngestedAtMs: z.number().nullable(),
    generatedAtMs: z.number()
});

// --- Departures --------------------------------------------------------------
/** How a departure is running, for at-a-glance colouring on the board. */
export const departureStatusSchema = z.union([z.literal("on_time"), z.literal("late"), z.literal("early"), z.literal("cancelled"), z.literal("skipped"), z.literal("scheduled")]);

export const departureSchema = z.object({
    tripId: z.string(),
    lineId: z.string(),
    lineName: z.string(),
    direction: directionSchema,
    /** GTFS headsign — where the train is going. Null when the trip is unmatched. */
    destination: z.string().nullable(),
    /** Timetabled departure (falls back to arrival), epoch seconds UTC. */
    scheduledTime: z.number().nullable(),
    /** The feed's live prediction, epoch seconds UTC. Null when cancelled. */
    predictedTime: z.number().nullable(),
    /** Positive = late. Null when the feed offers no prediction. */
    delaySeconds: z.number().nullable(),
    /** Whole minutes until `predictedTime`; negative once it is due. */
    minutesAway: z.number().nullable(),
    status: departureStatusSchema
});

export const stationDeparturesResponseSchema = z.object({
    stopId: z.string(),
    stopName: z.string(),
    departures: z.array(departureSchema),
    /** Minutes ahead the board looks. */
    horizonMinutes: z.number(),
    generatedAtMs: z.number()
});

// --- Trends --------------------------------------------------------------------
export const trendDirectionSchema = z.union([z.literal("improving"), z.literal("worsening"), z.literal("stable")]);

export const lineTrendSchema = z.object({
    lineId: z.string(),
    lineName: z.string(),
    /** On-time rate over the recent period, null when nothing ran. */
    recentOtpPercent: z.number().nullable(),
    /** The equal-length period immediately before it. */
    priorOtpPercent: z.number().nullable(),
    /** Percentage points, recent minus prior. */
    deltaPoints: z.number().nullable(),
    recentTrips: z.number(),
    priorTrips: z.number(),
    /**
     * "stable" also covers changes too small or too noisy to call — the app
     * never claims a trend it cannot distinguish from chance.
     */
    direction: trendDirectionSchema,
    /** False when either period is too thin to compare at all. */
    enoughData: z.boolean()
});

export const trendsResponseSchema = z.object({
    /** Length of each compared period, in days. */
    days: z.number(),
    recentFrom: z.string(),
    recentTo: z.string(),
    priorFrom: z.string(),
    priorTo: z.string(),
    thresholdSeconds: z.number(),
    lines: z.array(lineTrendSchema)
});

// --- Station rankings ----------------------------------------------------------
export const stationRankingSortSchema = z.union([z.literal("delay"), z.literal("amplification")]);

export const stationRankingSchema = z.object({
    stopId: z.string(),
    stopName: z.string(),
    lines: z.array(z.string()),
    avgArrivalDelaySeconds: z.number(),
    observations: z.number(),
    /**
     * Share of trains that arrived on time but left late — delay the station
     * itself introduces, rather than delay it inherited from up the line.
     */
    amplificationRatePercent: z.number().nullable(),
    arrivedWithin5Min: z.number(),
    lowSample: z.boolean()
});

export const stationRankingsResponseSchema = z.object({
    from: z.string(),
    to: z.string(),
    sort: stationRankingSortSchema,
    stations: z.array(stationRankingSchema),
    /** Stations excluded for having too few observations to rank fairly. */
    excludedLowSample: z.number()
});

// --- Delay propagation --------------------------------------------------------
/** Average delay at one stop along a line's route, in running order. */
export const propagationStopSchema = z.object({
    stopId: z.string(),
    stopName: z.string(),
    /** Position along the route, 1-based. */
    sequence: z.number(),
    avgDelaySeconds: z.number().nullable(),
    observations: z.number(),
    /**
     * Change in average delay since the previous stop. Positive = this segment
     * added delay; negative = trains recovered across it. Null at the first stop.
     */
    deltaSeconds: z.number().nullable()
});

/** A stop-to-stop segment ranked by how much delay it adds. */
export const propagationSegmentSchema = z.object({
    fromStopName: z.string(),
    toStopName: z.string(),
    addedSeconds: z.number()
});

export const propagationResponseSchema = z.object({
    lineId: z.string(),
    lineName: z.string(),
    direction: directionSchema,
    from: z.string(),
    to: z.string(),
    stops: z.array(propagationStopSchema),
    /** Segments that add the most delay, worst first. */
    worstSegments: z.array(propagationSegmentSchema),
    /** Segments where trains most reliably make time back. */
    bestRecoveries: z.array(propagationSegmentSchema),
    /** Delay at the last stop minus the first — the journey's net accumulation. */
    netAccumulatedSeconds: z.number().nullable()
});

// --- Commute -----------------------------------------------------------------
/** Reliability of one timetabled departure on a commute, over the period. */
export const commuteDepartureSchema = z.object({
    /** Minutes after local midnight, so departures sort and label consistently. */
    departureMinutes: z.number(),
    /** "7:42 AM". */
    label: z.string(),
    lineName: z.string(),
    /** Scheduled journey time in minutes; null if the timetable is incomplete. */
    scheduledMinutes: z.number().nullable(),
    observations: z.number(),
    cancellations: z.number(),
    /** Share arriving within the strict threshold. Null below the sample floor. */
    onTimePercent: z.number().nullable(),
    avgArrivalDelaySeconds: z.number().nullable(),
    /** The delay you should plan around — exceeded one journey in ten. */
    p90ArrivalDelaySeconds: z.number().nullable(),
    /** True when too few observations to draw a conclusion from. */
    lowSample: z.boolean()
});

export const commuteResponseSchema = z.object({
    origin: z.object({
        stopId: z.string(),
        stopName: z.string()
    }),
    destination: z.object({
        stopId: z.string(),
        stopName: z.string()
    }),
    from: z.string(),
    to: z.string(),
    /** Lines that actually ran this pair in the period. */
    linesServing: z.array(z.string()),
    observations: z.number(),
    cancellations: z.number(),
    cancellationRatePercent: z.number(),
    onTimePercent: z.number().nullable(),
    avgArrivalDelaySeconds: z.number().nullable(),
    p90ArrivalDelaySeconds: z.number().nullable(),
    /** Median observed journey time, minutes. Null when nothing completed. */
    medianJourneyMinutes: z.number().nullable(),
    /** Timetabled journey time, minutes. */
    scheduledJourneyMinutes: z.number().nullable(),
    /** Every timetabled departure on this pair, earliest first. */
    departures: z.array(commuteDepartureSchema),
    /** Most and least reliable departures with enough data to rank. */
    mostReliable: commuteDepartureSchema.nullable(),
    leastReliable: commuteDepartureSchema.nullable()
});

// --- Light rail --------------------------------------------------------------
export const lightRailLineMdbfSchema = z.object({
    lineName: z.string(),
    avgMdbf: z.number(),
    monthsCovered: z.number()
});

export const lightRailSummaryResponseSchema = z.object({
    from: z.string(),
    to: z.string(),
    /** Average systemwide light-rail OTP over the period (null if none). */
    otpPercent: z.number().nullable(),
    monthsCovered: z.number(),
    lines: z.array(lightRailLineMdbfSchema),
    /** Monthly systemwide light-rail OTP over the period, ascending. */
    otpTrend: z.array(z.object({
        month: z.string(),
        otpPercent: z.number()
    })),
    /** Months these figures cover; null if light rail data was never published. */
    coverage: publishedCoverageSchema.nullable()
});

// --- System -----------------------------------------------------------------
export const systemSummaryResponseSchema = z.object({
    from: z.string(),
    to: z.string(),
    overall: otpSummarySchema,
    njtOfficial: njtOfficialComparisonSchema.nullable(),
    njtCancellations: njtCancellationsSchema.nullable(),
    fleetMdbf: fleetMdbfSchema.nullable(),
    /** Months `njtOfficial` / `njtCancellations` cover; null if never published. */
    officialCoverage: publishedCoverageSchema.nullable(),
    /** Months `fleetMdbf` covers (published separately from per-line OTP). */
    fleetMdbfCoverage: publishedCoverageSchema.nullable()
});

export const heatmapResponseSchema = z.object({
    from: z.string(),
    to: z.string(),
    type: heatmapTypeSchema,
    buckets: z.array(heatmapBucketResultSchema)
});

// --- Lines ------------------------------------------------------------------
export const lineListItemSchema = z.object({
    /** Public identifier used in API paths and deep links (the GTFS route_id). */
    id: z.string(),
    slug: z.string(),
    name: z.string(),
    shortName: z.string(),
    hasAmtrakAttribution: z.boolean(),
    /** Official NJT route color (hex, no leading #), null if unknown. */
    color: z.string().nullable(),
    /** NJT's reported OTP for the most recent published month (null if none). */
    njtOtpPercent: z.number().nullable(),
    njtCancellationRatePercent: z.number().nullable(),
    /** The month those NJT figures are from, `YYYY-MM` (null if none). */
    njtLatestMonth: z.string().nullable()
});

export const lineListResponseSchema = z.object({
    lines: z.array(lineListItemSchema)
});

export const lineSummaryResponseSchema = z.object({
    lineId: z.string(),
    name: z.string(),
    from: z.string(),
    to: z.string(),
    overall: otpSummarySchema,
    inbound: otpSummarySchema,
    outbound: otpSummarySchema,
    njtOfficial: njtOfficialComparisonSchema.nullable(),
    njtCancellations: njtCancellationsSchema.nullable(),
    /** Months `njtOfficial` / `njtCancellations` cover; null if never published. */
    officialCoverage: publishedCoverageSchema.nullable()
});

export const trendPointSchema = z.object({
    date: z.string(),
    otpPercent15Min: z.number(),
    cancellationRatePercent: z.number(),
    tripsOperated: z.number(),
    /** NJT's reported 6-min OTP for the month this point falls in, if available. */
    njtOfficialOtpPercent: z.number().nullable()
});

export const lineTrendResponseSchema = z.object({
    lineId: z.string(),
    from: z.string(),
    to: z.string(),
    interval: z.union([z.literal("daily"), z.literal("weekly")]),
    njtThresholdSeconds: z.number(),
    points: z.array(trendPointSchema)
});

export const monthlyComparisonRowSchema = z.object({
    /** `YYYY-MM`. */
    month: z.string(),
    /** NJT's reported 6-minute OTP for the month, null if not published. */
    njtOtpPercent: z.number().nullable(),
    njtOtpPercentAmtrakAdjusted: z.number().nullable(),
    /** This project's OTP at the 15-minute threshold, null if no data that month. */
    projectOtpPercent15Min: z.number().nullable(),
    projectTripsOperated: z.number()
});

export const lineMonthlyResponseSchema = z.object({
    lineId: z.string(),
    name: z.string(),
    rows: z.array(monthlyComparisonRowSchema)
});

/** Average NJT OTP for a calendar month (1-12) across all available years. */
export const seasonalityMonthSchema = z.object({
    month: z.number(),
    avgOtpPercent: z.number().nullable(),
    years: z.number()
});

/** Average NJT OTP for a calendar year. */
export const annualOtpYearSchema = z.object({
    year: z.number(),
    avgOtpPercent: z.number().nullable(),
    months: z.number()
});

/** Long-run NJT history for a scope: seasonality (by month) + annual trend. */
export const historyResponseSchema = z.object({
    scopeLabel: z.string(),
    seasonality: z.array(seasonalityMonthSchema),
    annual: z.array(annualOtpYearSchema),
    /** Fleet mean-distance-between-failures by year (system scope only). */
    mdbfAnnual: z.array(z.object({
        year: z.number(),
        avgMdbf: z.number()
    })).optional()
});

export const worstTripSchema = z.object({
    tripId: z.string(),
    routeId: z.string(),
    lineName: z.string(),
    direction: directionSchema,
    terminalStopName: z.string(),
    avgTerminalDelaySeconds: z.number(),
    observations: z.number()
});

export const worstTripsResponseSchema = z.object({
    scopeLabel: z.string(),
    from: z.string(),
    to: z.string(),
    trips: z.array(worstTripSchema)
});

// --- Stations ---------------------------------------------------------------
export const stationListItemSchema = z.object({
    stopId: z.string(),
    stopName: z.string(),
    lines: z.array(z.string())
});

export const stationListResponseSchema = z.object({
    stations: z.array(stationListItemSchema)
});

export const stationLineDirectionDelaySchema = z.object({
    lineName: z.string(),
    direction: directionSchema,
    avgArrivalDelaySeconds: z.number(),
    observations: z.number()
});

export const stationSummaryResponseSchema = z.object({
    stopId: z.string(),
    stopName: z.string(),
    from: z.string(),
    to: z.string(),
    byLineDirection: z.array(stationLineDirectionDelaySchema),
    delayDistribution: z.array(distributionBucketResultSchema),
    hourOfDay: z.array(heatmapBucketResultSchema),
    amplification: z.object({
        arrivedWithin5Min: z.number(),
        departedLate: z.number(),
        amplificationRatePercent: z.number()
    })
});

// --- Connections ------------------------------------------------------------
export const connectionDayOfWeekResultSchema = z.object({
    dayOfWeek: z.number(),
    observations: z.number(),
    successes: z.number(),
    successRatePercent: z.number()
});

export const connectionRateResultSchema = z.object({
    observations: z.number(),
    successes: z.number(),
    successRatePercent: z.number()
});

export const connectionResponseSchema = z.object({
    inboundTripId: z.string(),
    transferStopId: z.string(),
    outboundTripId: z.string(),
    from: z.string(),
    to: z.string(),
    observations: z.number(),
    successes: z.number(),
    successRatePercent: z.number(),
    byDayOfWeek: z.array(connectionDayOfWeekResultSchema),
    peak: connectionRateResultSchema,
    offPeak: connectionRateResultSchema,
    inboundDelayDistribution: z.array(distributionBucketResultSchema),
    lowSample: z.boolean()
});

export const connectionTopItemSchema = z.object({
    inboundTripId: z.string(),
    transferStopId: z.string(),
    transferStopName: z.string(),
    outboundTripId: z.string(),
    observations: z.number()
});

export const connectionTopResponseSchema = z.object({
    transfers: z.array(connectionTopItemSchema)
});

// --- Alerts -----------------------------------------------------------------
export const alertListItemSchema = z.object({
    alertId: z.string(),
    affectedRoutes: z.array(z.string()),
    affectedStops: z.array(z.string()),
    headerText: z.string(),
    descriptionText: z.string(),
    effectType: z.string(),
    activeFrom: z.number().nullable(),
    activeTo: z.number().nullable(),
    ingestedAtMs: z.number()
});

export const alertListResponseSchema = z.object({
    alerts: z.array(alertListItemSchema),
    page: z.number(),
    pageSize: z.number(),
    total: z.number()
});

export const alertFrequencyLineSchema = z.object({
    lineName: z.string(),
    counts: z.record(z.string(), z.number()),
    total: z.number()
});

export const alertFrequencyResponseSchema = z.object({
    from: z.string(),
    to: z.string(),
    byLine: z.array(alertFrequencyLineSchema)
});

/**
 * One predicted leg, as the app shows it.
 *
 * Station *names* rather than the ids the model works in: the modelling repo
 * deals in GTFS ids and the app renders places people recognise, and resolving
 * that here keeps a screen from having to join two payloads.
 */
/**
 * The range a model puts a delay in, and how sure it is.
 *
 * A range is a more honest thing to show a rider than a point: "5 to 12 minutes
 * late" says what a single "8.4" cannot, which is how much the model does not
 * know. Null where the run produced only a point estimate — most days, until
 * the modelling repo publishes conformal intervals.
 */
export const predictionIntervalSchema = z.object({
    /** Lower bound, seconds; positive = late. */
    lowerSeconds: z.number(),
    /** Upper bound, seconds. */
    upperSeconds: z.number(),
    /** Coverage: 80 means 8 runs in 10 are expected to land inside the range. */
    percent: z.number()
});

export const predictedDelaySchema = z.object({
    tripId: z.string(),
    lineName: z.string(),
    fromStopName: z.string(),
    toStopName: z.string(),
    /** How far ahead the prediction reaches, in seconds. */
    horizonSeconds: z.number(),
    /** Predicted delay at the destination, seconds; positive = late. */
    predictedDelaySeconds: z.number(),
    /** The range around that estimate, or null when the model published none. */
    interval: predictionIntervalSchema.nullable(),
    /** Observed delay once the trip has run, or null while it is still ahead. */
    actualDelaySeconds: z.number().nullable(),
    /** Signed error once both are known: positive = the model was optimistic. */
    errorSeconds: z.number().nullable()
});

/**
 * What produced a set of predictions.
 *
 * Shown with the numbers rather than alongside them optionally. A forecast with
 * no provenance invites more confidence than it has earned, and this is the
 * difference between "a model said this" and "the data says this".
 */
export const predictionProvenanceSchema = z.object({
    modelVersion: z.string(),
    runId: z.string(),
    /** When the most recent prediction was made, epoch seconds UTC. */
    predictedAtEpochSeconds: z.number()
});

/**
 * `GET /predictions?date=` — model output for one service date.
 *
 * `available: false` is the normal state until the modelling repo has run, not
 * an error: this project publishes no synthetic data, so an unpredicted day says
 * so rather than showing a plausible number.
 */
export const predictionsResponseSchema = z.object({
    serviceDate: z.string(),
    available: z.boolean(),
    /** Service dates that do hold predictions, so a screen can offer them. */
    availableDates: z.array(z.string()),
    /** Lines with predictions on this date, for filtering. */
    lines: z.array(z.string()),
    provenance: predictionProvenanceSchema.nullable(),
    /**
     * The most delayed legs, largest first — not everything.
     *
     * A service date holds ~50,000 legs, which is ~5 MB of JSON and 300 KB of DOM,
     * and most of them are a shuttle predicted to be on time. The rider's question
     * is about the trains in trouble, so the response carries those and
     * `totalPredictions` says how many there were.
     */
    predictions: z.array(predictedDelaySchema),
    /** How many legs were predicted for this date, before the cap. */
    totalPredictions: z.number(),
    /**
     * Mean absolute error over the legs whose actual is known, or null when none
     * are. The honest headline: how wrong the model has been, not how confident.
     */
    meanAbsoluteErrorSeconds: z.number().nullable(),
    /** How many legs have an actual to compare against. */
    scoredCount: z.number()
});
