// Generated by ts-to-zod
import { z } from "zod";

/**
 * Core domain entities. Instants are epoch seconds (UTC) unless the field name
 * ends in `Ms`. `serviceDate` is the GTFS calendar date, `YYYY-MM-DD` — an
 * after-midnight trip keeps the prior day's service date.
 */
export const directionSchema = z.union([z.literal("inbound"), z.literal("outbound")]);

export const feedTypeSchema = z.union([z.literal("TripUpdates"), z.literal("VehiclePositions"), z.literal("ServiceAlerts")]);

/** GTFS-realtime Alert.Effect, normalized to a small closed set. */
export const effectTypeSchema = z.union([z.literal("delay"), z.literal("cancellation"), z.literal("detour"), z.literal("reduced_service"), z.literal("additional_service"), z.literal("modified_service"), z.literal("no_service"), z.literal("stop_moved"), z.literal("other"), z.literal("unknown")]);

/** One row per (trip, stop, service date): the observed delay at that stop. */
export const tripStopEventSchema = z.object({
    tripId: z.string(),
    routeId: z.string(),
    lineName: z.string(),
    stopId: z.string(),
    stopName: z.string(),
    /**
     * @format int
     * @unit stop_index
     */
    stopSequence: z.int(),
    direction: directionSchema,
    /** GTFS service date, `YYYY-MM-DD`. */
    serviceDate: z.string(),
    /**
     * Scheduled arrival, epoch seconds UTC (null if the stop has no arrival time).
     * @format int
     * @unit epoch_seconds
     */
    scheduledArrival: z.int().nullable(),
    /**
     * @format int
     * @unit epoch_seconds
     */
    scheduledDeparture: z.int().nullable(),
    /**
     * Predicted/observed arrival at the time of the final reading, epoch seconds UTC.
     * @format int
     * @unit epoch_seconds
     */
    observedArrival: z.int().nullable(),
    /**
     * Positive = late, negative = early. Null when not yet observed.
     * @format int
     * @unit seconds
     */
    delaySeconds: z.int().nullable(),
    stopSkipped: z.boolean(),
    tripCancelled: z.boolean(),
    /** Which GTFS static snapshot the trip was matched against. */
    gtfsStaticVersion: z.string(),
    /**
     * When this reading was ingested, epoch milliseconds.
     * @format int
     * @unit epoch_milliseconds
     */
    ingestedAtMs: z.int()
});

/** GTFS-realtime VehicleStopStatus. */
export const vehicleStopStatusSchema = z.union([z.literal("incoming_at"), z.literal("stopped_at"), z.literal("in_transit_to")]);

export const serviceAlertSchema = z.object({
    alertId: z.string(),
    affectedRoutes: z.array(z.string()),
    affectedStops: z.array(z.string()),
    headerText: z.string(),
    descriptionText: z.string(),
    effectType: effectTypeSchema,
    /** epoch seconds UTC, null if open-ended. */
    activeFrom: z.number().nullable(),
    activeTo: z.number().nullable(),
    ingestedAtMs: z.number()
});

export const gtfsStaticVersionSchema = z.object({
    versionId: z.string(),
    /** epoch seconds UTC when this schedule became effective. */
    effectiveFrom: z.number(),
    /** epoch seconds UTC when superseded, null while current. */
    effectiveTo: z.number().nullable(),
    /** sha256 of the GTFS zip, used to detect changes. */
    checksum: z.string(),
    ingestedAtMs: z.number()
});

export const officialNjtMetricSchema = z.object({
    /** 1-12 */
    month: z.number(),
    year: z.number(),
    lineName: z.string(),
    /** NJT definition: within 6 minutes. */
    otpPercent: z.number(),
    /** Amtrak-adjusted OTP for NEC / NJCL; null where not reported. */
    otpPercentAmtrakAdjusted: z.number().nullable(),
    tripsOperated: z.number(),
    cancellations: z.number(),
    /**
     * NJT's cause category → count. Null when not imported. The AMTRAK entry is
     * the Amtrak-attributed share NJT excludes from its adjusted figures.
     */
    cancellationCauses: z.record(z.string(), z.number()).nullable()
});

/** NJT's systemwide fleet Mean Distance Between Failures (miles), monthly. */
export const fleetMdbfMetricSchema = z.object({
    month: z.number(),
    year: z.number(),
    /** Miles between failures. */
    mdbf: z.number()
});

/** Systemwide light rail on-time performance, monthly. */
export const lightRailOtpMetricSchema = z.object({
    year: z.number(),
    month: z.number(),
    otpPercent: z.number()
});

/** Per-line light rail Mean Distance Between Failures (miles), monthly. */
export const lightRailMdbfMetricSchema = z.object({
    year: z.number(),
    month: z.number(),
    lineName: z.string(),
    mdbf: z.number()
});

/**
 * Where a train is right now. Each poll returns a complete snapshot of active
 * vehicles, so the stored set is replaced wholesale rather than accumulated;
 * history stays recoverable from `raw_snapshots`.
 */
export const vehiclePositionSchema = z.object({
    vehicleId: z.string(),
    tripId: z.string().nullable(),
    routeId: z.string().nullable(),
    lineName: z.string().nullable(),
    direction: directionSchema.nullable(),
    latitude: z.number(),
    longitude: z.number(),
    /** Degrees clockwise from true north. */
    bearing: z.number().nullable(),
    speedMetersPerSecond: z.number().nullable(),
    /** GTFS `stop_id` this reading is relative to. */
    stopId: z.string().nullable(),
    stopName: z.string().nullable(),
    status: vehicleStopStatusSchema.nullable(),
    /** When the vehicle reported this position, epoch seconds UTC. */
    reportedAt: z.number().nullable(),
    ingestedAtMs: z.number()
});
